name: mainelopment workflow

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: 04-06-2025            
  PROJECT_FOLDER: Shared
  ORCH_URL: https://cloud.uipath.com/testbfsvyha/DefaultTenant
  ORCH_TENANT: DefaultTenant
  ORCH_CLIENT_ID: 21a6955b-2fbe-4cd4-8d71-4124dff739ce.Trim()
  ORCH_USER_KEY: "@cmd^Q!l46F89)6O"
  ORCH_ACC_NAME: testbfsvyha

jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: Echo default environment variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"

  cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Clean previous workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build-uipath-nuget-package:
    needs: cleaner
    runs-on: windows-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build NuGet Package
        shell: pwsh
        run: |
          pwsh "${{ github.workspace }}/scripts/UiPathPack.ps1" `
            "${{ github.workspace }}/project.json" `
            -destination_folder "${{ github.workspace }}/package"

      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            package/*
            scripts/*.ps1

  publish-uipath-nuget-package:
    needs: build-uipath-nuget-package
    runs-on: windows-latest
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Publish Nuget Package to main
        shell: pwsh
        run: ${{ github.workspace }}\scripts\UiPathDeploy.ps1 ${{ github.workspace }}\package ${{env.ORCH_URL}} ${{env.ORCH_TENANT}} -UserKey ${{env.ORCH_USER_KEY}} -account_name ${{env.ORCH_ACC_NAME}}
   
  test-uipath-published-package:
    needs: publish-uipath-nuget-package
    runs-on: windows-latest  
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Test the Package With Test Cases 
        run: ${{ github.workspace }}\scripts\\UiPathRunTest.ps1  ${{env.ORCH_URL}} ${{env.ORCH_TENANT}} -UserKey ${{env.ORCH_USER_KEY}} -account_name ${{env.ORCH_ACC_NAME}} -testset "04062025TestSet"
