env:
  PROJECT_NAME: 04062025
  PROJECT_FOLDER: Shared
  ORCH_URL: https://cloud.uipath.com/uipatntvskhu/DefaultTenant/
  ORCH_TENANT: DefaultTenant
  ORCH_ACC_NAME: uipatntvskhu
  UIPATH_SCOPE: ${{ secrets.UIPATH_SCOPE }}

jobs:
  ...
  publish-uipath-nuget-package:
    needs: build-uipath-nuget-package
    runs-on: windows-latest
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts

      - name: Get OAuth Access Token
        id: get_token
        shell: pwsh
        run: |
          $body = @{
            grant_type = "client_credentials"
            client_id = "${{ secrets.UIPATH_CLIENT_ID }}"
            client_secret = "${{ secrets.UIPATH_CLIENT_SECRET }}"
            scope = "${{ secrets.UIPATH_SCOPE }}"
          }
          $response = Invoke-RestMethod -Uri "https://cloud.uipath.com/identity_/connect/token" `
            -Method Post `
            -ContentType "application/x-www-form-urlencoded" `
            -Body $body
          "access_token=$($response.access_token)" >> $env:GITHUB_OUTPUT

      - name: Publish Nuget Package to main
        shell: pwsh
        run: |
          $token = "${{ steps.get_token.outputs.access_token }}"
          pwsh "${{ github.workspace }}\scripts\UiPathDeploy.ps1" `
            "${{ github.workspace }}\package" `
            "${{env.ORCH_URL}}" `
            "${{env.ORCH_TENANT}}" `
            -Token $token `
            -account_name "${{env.ORCH_ACC_NAME}}" `
            -folder_organization_unit "${{env.PROJECT_FOLDER}}"

  test-uipath-published-package:
    needs: publish-uipath-nuget-package
    runs-on: windows-latest  
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts

      - name: Get OAuth Access Token
        id: get_token
        shell: pwsh
        run: |
          $body = @{
            grant_type = "client_credentials"
            client_id = "${{ secrets.UIPATH_CLIENT_ID }}"
            client_secret = "${{ secrets.UIPATH_CLIENT_SECRET }}"
            scope = "${{ secrets.UIPATH_SCOPE }}"
          }
          $response = Invoke-RestMethod -Uri "https://cloud.uipath.com/identity_/connect/token" `
            -Method Post `
            -ContentType "application/x-www-form-urlencoded" `
            -Body $body
          "access_token=$($response.access_token)" >> $env:GITHUB_OUTPUT

      - name: Test the Package With Test Cases 
        run: |
          $token = "${{ steps.get_token.outputs.access_token }}"
          pwsh "${{ github.workspace }}\scripts\UiPathRunTest.ps1" `
            "${{env.ORCH_URL}}" `
            "${{env.ORCH_TENANT}}" `
            -Token $token `
            -account_name "${{env.ORCH_ACC_NAME}}" `
            -testset "Testset"
